defaults: &defaults
  adapter: mysql2
  username: root
  host: 127.0.0.1
  username: root
  pool: 5
  timeout: 5000

development:
  database: giveone_dev
  <<: *defaults

test:
  database: giveone_test
  <<: *defaults

staging:
  adapter: mysql2
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>
  pool: <%= ENV['DB_POOL'] %>
  reconnect: true
  schema_search_path: "public,shared_extensions"

production:
  adapter: mysql2
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>
  pool: <%= ENV['DB_POOL'] %>
  reconnect: true
  schema_search_path: "public,shared_extensions"
