# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b07739760c3c6442b6545a9edcfa97e0c8cd3b3496ef27614246806fe8bcf6682b7d82c5259008a5939e277fc0a7725e96c1dcbab57c3b34a555f0d97a5bfe0b
  name: <%= ENV["NAME"] %>
  description: <%=["DESCRIPTION"] %>
  address: <%= ENV["ADDRESS"] %>
  stripe_secret_key: <%= ENV["STRIPE_SECRET_KEY"] %>
  stripe_publishable_key: <%= ENV["STRIPE_PUBLISHABLE_KEY"] %>
  stripe_account_id: <%= ENV["STRIPE_ACCOUNT_ID"] %>
  mailchimp_api_key: <%= ENV["MAILCHIMP_API_KEY"] %>
  mailchimp_subscribers_list_id: <%= ENV["MAILCHIMP_SUBSCRIBERS_LIST_ID"] %>
  mailchimp_donors_list_id: <%= ENV["MAILCHIMP_DONORS_LIST_ID"] %>
  mandrill_api_key: <%= ENV["MANDRILL_API_KEY"] %>
  mandrill_username: <%= ENV["MANDRILL_USERNAME"] %>
  ein: <%= ENV["EIN"] %>
  developer_email: <%= ENV["DEVELOPER_EMAIL"] %>
  host: <%= ENV["HOST"] %>
  protocol: <%= ENV["PROTOCOL"] %>
  paperclip_bucket: <%= ENV["PAPERCLIP_BUCKET"] %>
  cloudfront_hostname: <%= ENV["CLOUDFRONT_HOSTNAME"] %>
  google_analytics_id: <%= ENV["GOOGLE_ANALYTICS_ID"] %>
  facebook_app_id: <%= ENV["FACEBOOK_APP_ID"] %>
  twitter_username: <%= ENV["TWITTER_USERNAME"] %>
  facebook_username: <%= ENV["FACEBOOK_USERNAME"] %>
  instagram_username: <%= ENV["INSTAGRAM_USERNAME"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  devise_secret_key: <%= ENV["DEVISE_SECRET_KEY"] %>
  paperclip_aws_access_key_id: <%= ENV["PAPERCLIP_AWS_ACCESS_KEY_ID"] %>
  paperclip_aws_secret_access_key: <%= ENV["PAPERCLIP_AWS_SECRET_ACCESS_KEY"] %>

test:
  secret_key_base: d70e4ecde1e8378f922148b6e75922e7ed24b8b6293098667459f944366e7f9fe309f76f8668d9ce3953db74916c3bb454e062595bc1cc41df181c2441b2c1e1
  name: Company Name
  description: Company Description
  address: Company Description # for Stripe receipt emails, etc
  stripe_secret_key: sk_test_abc
  stripe_publishable_key: pk_test_def
  stripe_account_id: acct_ghi
  mailchimp_api_key: mailchimp_api_key_123
  mailchimp_subscribers_list_id: subscribers
  mailchimp_donors_list_id: donors
  mandrill_api_key: mandrill_api_key_123
  mandrill_username: mandrill
  ein: 81-5555555
  developer_email: admin@example.com
  host: host
  protocol: http
  paperclip_bucket: test
  cloudfront_hostname: foo.cloudfront.net
  google_analytics_id: UA-00000000-0
  facebook_app_id: 1
  twitter_username: 2
  facebook_username: 3
  instagram_username: 4
  aws_access_key_id: aws_access_key_id
  aws_secret_access_key: aws_secret_access_key
  devise_secret_key: 264797acf27e6f1f401308bda4b9a305d4212a4c423f105a7e6088c0af05401c084519d8b1713a247e62dc81f32ffd40f3d336df3f16029bf0f790bf81e769cb
  paperclip_aws_access_key_id: paperclip_aws_access_key_id
  paperclip_aws_secret_access_key: paperclip_aws_secret_access_key

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  name: <%= ENV["NAME"] %>
  description: <%=["DESCRIPTION"] %>
  address: <%= ENV["ADDRESS"] %>
  stripe_secret_key: <%= ENV["STRIPE_SECRET_KEY"] %>
  stripe_publishable_key: <%= ENV["STRIPE_PUBLISHABLE_KEY"] %>
  stripe_account_id: <%= ENV["STRIPE_ACCOUNT_ID"] %>
  mailchimp_api_key: <%= ENV["MAILCHIMP_API_KEY"] %>
  mailchimp_subscribers_list_id: <%= ENV["MAILCHIMP_SUBSCRIBERS_LIST_ID"] %>
  mailchimp_donors_list_id: <%= ENV["MAILCHIMP_DONORS_LIST_ID"] %>
  mandrill_api_key: <%= ENV["MANDRILL_API_KEY"] %>
  mandrill_username: <%= ENV["MANDRILL_USERNAME"] %>
  ein: <%= ENV["EIN"] %>
  developer_email: <%= ENV["DEVELOPER_EMAIL"] %>
  host: <%= ENV["HOST"] %>
  protocol: <%= ENV["PROTOCOL"] %>
  paperclip_bucket: <%= ENV["PAPERCLIP_BUCKET"] %>
  cloudfront_hostname: <%= ENV["CLOUDFRONT_HOSTNAME"] %>
  google_analytics_id: <%= ENV["GOOGLE_ANALYTICS_ID"] %>
  facebook_app_id: <%= ENV["FACEBOOK_APP_ID"] %>
  twitter_username: <%= ENV["TWITTER_USERNAME"] %>
  facebook_username: <%= ENV["FACEBOOK_USERNAME"] %>
  instagram_username: <%= ENV["INSTAGRAM_USERNAME"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  devise_secret_key: <%= ENV["DEVISE_SECRET_KEY"] %>
  paperclip_aws_access_key_id: <%= ENV["PAPERCLIP_AWS_ACCESS_KEY_ID"] %>
  paperclip_aws_secret_access_key: <%= ENV["PAPERCLIP_AWS_SECRET_ACCESS_KEY"] %>
