development:
  secret_key: <%= ENV["STRIPE_SECRET_KEY"] %>
  publishable_key: <%= ENV["STRIPE_PUBLISHABLE_KEY"] %>
  account_id: <%= ENV["STRIPE_ACCOUNT_ID"] %>

test:
  secret_key: sk_test_abc
  publishable_key: pk_test_def
  account_id: acct_ghi

production:
  secret_key: <%= ENV["STRIPE_SECRET_KEY"] %>
  publishable_key: <%= ENV["STRIPE_PUBLISHABLE_KEY"] %>
  account_id: <%= ENV["STRIPE_ACCOUNT_ID"] %>
